name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'   # Only trigger when code in the backend folder changes 
  workflow_dispatch:     

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install necessary dependencies
      run:  |
        cd starter/backend
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run Lint
      run: cd starter/backend && pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses:  actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install necessary dependencies
      run:  |
        cd starter/backend
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run Tests
      run: cd starter/backend && pipenv install pytest && pipenv run test

      
  Build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and tag the Docker image
      run: |
        cd starter/backend
        docker build --tag mp-backend:latest .

